import type { Season, Style } from '@/lib/types'

/** IndexedDB 최초 시드용 목업. 브랜드 seed id와 맞춰 둔다. */
export const SEED_SEASONS: Season[] = [
  {
    id: 'season-atelier-26ss',
    brandId: 'brand-atelier',
    code: '26SS',
    name: 'SS',
    releaseTiming: '26.03 말',
    year: 2026,
    status: 'active',
  },
  {
    id: 'season-atelier-25fw',
    brandId: 'brand-atelier',
    code: '25FW',
    name: 'FW',
    releaseTiming: '25.09',
    year: 2025,
    status: 'archived',
  },
  {
    id: 'season-noir-26ss',
    brandId: 'brand-noir',
    code: '26SS',
    name: 'SS',
    releaseTiming: '26.03 말',
    year: 2026,
    status: 'active',
  },
  {
    id: 'season-noir-25fw',
    brandId: 'brand-noir',
    code: '25FW',
    name: 'FW',
    releaseTiming: '25.09',
    year: 2025,
    status: 'archived',
  },
  {
    id: 'season-lumen-25fw',
    brandId: 'brand-lumen',
    code: '25FW',
    name: 'FW',
    releaseTiming: '25.09',
    year: 2025,
    status: 'archived',
  },
  {
    id: 'season-lumen-26ss',
    brandId: 'brand-lumen',
    code: '26SS',
    name: 'SS',
    releaseTiming: '26.03 말',
    year: 2026,
    status: 'active',
  },
  {
    id: 'season-form-26ss',
    brandId: 'brand-form',
    code: '26SS',
    name: 'SS',
    releaseTiming: '26.03 말',
    year: 2026,
    status: 'active',
  },
]

export const SEED_STYLES: Style[] = [
  {
    id: 'style-a1',
    brandId: 'brand-atelier',
    seasonId: 'season-atelier-26ss',
    styleNo: 'AT-26SS-001',
    name: '오버사이즈 트렌치',
    category: '아우터',
    gender: 'W',
    colors: ['Ivory', 'Black'],
    targetCost: 89000,
    plannedQty: 400,
    retailPrice: 289000,
    status: 'design',
    designer: '김서연',
    planner: '박민지',
    thumbnailColor: '#E8E0D5',
    description: '코튼 혼방 오버사이즈 트렌치. 벨트 디테일.',
    values: { fabric: 'Cotton-nylon blend 180g' },
  },
  {
    id: 'style-a2',
    brandId: 'brand-atelier',
    seasonId: 'season-atelier-26ss',
    styleNo: 'AT-26SS-002',
    name: '실크 블라우스',
    category: '상의',
    gender: 'W',
    colors: ['Cream', 'Sage'],
    targetCost: 42000,
    plannedQty: 600,
    retailPrice: 149000,
    status: 'sampling',
    designer: '김서연',
    planner: '박민지',
    thumbnailColor: '#D4C5B0',
    description: '실크 블렌드 블라우스. 히든 플acket.',
    values: { fabric: 'Silk blend georgette' },
  },
  {
    id: 'style-a3',
    brandId: 'brand-atelier',
    seasonId: 'season-atelier-26ss',
    styleNo: 'AT-26SS-003',
    name: '와이드 슬랙스',
    category: '하의',
    gender: 'W',
    colors: ['Charcoal', 'Stone'],
    targetCost: 38000,
    plannedQty: 800,
    retailPrice: 129000,
    status: 'confirmed',
    designer: '이하늘',
    planner: '박민지',
    thumbnailColor: '#6B6B6B',
    values: { orderQty: '800', channel: '온라인' },
  },
  {
    id: 'style-a4',
    brandId: 'brand-atelier',
    seasonId: 'season-atelier-25fw',
    styleNo: 'AT-25FW-014',
    name: '울 블렌드 코트',
    category: '아우터',
    gender: 'W',
    colors: ['Camel', 'Navy'],
    targetCost: 120000,
    plannedQty: 280,
    retailPrice: 420000,
    status: 'received',
    designer: '김서연',
    planner: '박민지',
    thumbnailColor: '#C4A484',
    values: {
      orderQty: '280',
      channel: '자사몰/편집샵',
      warehouse: '김포 물류센터',
      onHand: '84',
    },
  },
  {
    id: 'style-a5',
    brandId: 'brand-atelier',
    seasonId: 'season-atelier-26ss',
    styleNo: 'AT-26SS-004',
    name: '니트 카디건',
    category: '니트',
    gender: 'W',
    colors: ['Oatmeal', 'Navy'],
    targetCost: 35000,
    plannedQty: 500,
    retailPrice: 119000,
    status: 'draft',
    designer: '이하늘',
    planner: '박민지',
    thumbnailColor: '#E5D5C0',
    values: {},
  },
  {
    id: 'style-n1',
    brandId: 'brand-noir',
    seasonId: 'season-noir-26ss',
    styleNo: 'NR-26SS-001',
    name: '블랙 테일러드 자켓',
    category: '아우터',
    gender: 'U',
    colors: ['Black'],
    targetCost: 95000,
    plannedQty: 320,
    retailPrice: 320000,
    status: 'design',
    designer: '최유진',
    planner: '정호준',
    thumbnailColor: '#222222',
    values: { fabric: 'Wool blend 240g' },
  },
  {
    id: 'style-n2',
    brandId: 'brand-noir',
    seasonId: 'season-noir-26ss',
    styleNo: 'NR-26SS-002',
    name: '스트레이트 팬츠',
    category: '하의',
    gender: 'U',
    colors: ['Black', 'Ink'],
    targetCost: 40000,
    plannedQty: 500,
    retailPrice: 145000,
    status: 'confirmed',
    designer: '최유진',
    planner: '정호준',
    thumbnailColor: '#111111',
    values: { orderQty: '500', channel: '온라인' },
  },
  {
    id: 'style-n3',
    brandId: 'brand-noir',
    seasonId: 'season-noir-25fw',
    styleNo: 'NR-25FW-008',
    name: '롱 울 코트',
    category: '아우터',
    gender: 'U',
    colors: ['Black', 'Graphite'],
    targetCost: 140000,
    plannedQty: 200,
    retailPrice: 480000,
    status: 'ordered',
    designer: '최유진',
    planner: '정호준',
    thumbnailColor: '#2B2B2B',
    values: {
      orderQty: '200',
      channel: '편집샵',
      warehouse: '김포 물류센터',
      onHand: '0',
    },
  },
  {
    id: 'style-l1',
    brandId: 'brand-lumen',
    seasonId: 'season-lumen-26ss',
    styleNo: 'LM-26SS-001',
    name: '라이트 코튼 셔츠',
    category: '상의',
    gender: 'U',
    colors: ['White', 'Sky'],
    targetCost: 22000,
    plannedQty: 1200,
    retailPrice: 79000,
    status: 'design',
    designer: '한소희',
    planner: '오세훈',
    thumbnailColor: '#E8F0F5',
    values: {},
  },
  {
    id: 'style-l2',
    brandId: 'brand-lumen',
    seasonId: 'season-lumen-25fw',
    styleNo: 'LM-25FW-012',
    name: '플리스 후디',
    category: '상의',
    gender: 'U',
    colors: ['Grey', 'Olive'],
    targetCost: 28000,
    plannedQty: 900,
    retailPrice: 99000,
    status: 'received',
    designer: '한소희',
    planner: '오세훈',
    thumbnailColor: '#A8B0A0',
    values: {
      orderQty: '900',
      channel: '전 채널',
      warehouse: '김포 물류센터',
      onHand: '180',
    },
  },
  {
    id: 'style-f1',
    brandId: 'brand-form',
    seasonId: 'season-form-26ss',
    styleNo: 'FM-26SS-001',
    name: '카고 팬츠',
    category: '하의',
    gender: 'U',
    colors: ['Olive', 'Sand'],
    targetCost: 36000,
    plannedQty: 700,
    retailPrice: 135000,
    status: 'sampling',
    designer: '배수진',
    planner: '윤재민',
    thumbnailColor: '#6B705C',
    values: {
      fabric: 'Ripstop cotton',
      orderQty: '0',
      channel: '미정',
    },
  },
  {
    id: 'style-f2',
    brandId: 'brand-form',
    seasonId: 'season-form-26ss',
    styleNo: 'FM-26SS-002',
    name: '유틸 필드 자켓',
    category: '아우터',
    gender: 'U',
    colors: ['Khaki', 'Black'],
    targetCost: 72000,
    plannedQty: 350,
    retailPrice: 248000,
    status: 'design',
    designer: '배수진',
    planner: '윤재민',
    thumbnailColor: '#8B7E66',
    values: {},
  },
]
