import type { FolderGroup } from '../types'
import { getFolderDisplayName, getImmediateChildFolders } from '../file-manager-utils'

interface Props { browseTypes: string[]; activeType: string | null; activeFolder: string | null; groups: FolderGroup[]; busy: boolean; status: { message: string; kind: string }; selectType: (type: string | null) => void; selectFolder: (folder: string) => void; refresh: () => void; menu: (event: React.MouseEvent, type: string, folder?: string) => void }
export function ServerTreeSidebar({ browseTypes, activeType, activeFolder, groups, busy, status, selectType, selectFolder, refresh, menu }: Props) {
  const folders = (parent: string | null) => getImmediateChildFolders(groups, parent)
  const node = (folder: string) => <div key={folder}><button className={`tree-item${activeFolder === folder ? ' active' : ''}`} onClick={() => selectFolder(folder)} onContextMenu={(event) => menu(event, activeType || '', folder)}><span className="tree-icon">·</span><span className="tree-name">{getFolderDisplayName(folder)}</span></button>{folders(folder).length > 0 && <div className="tree-children">{folders(folder).map(node)}</div>}</div>
  return <aside className="sidebar"><button className="sidebar-brand" disabled={busy} title="새로고침" onClick={refresh}>masmarulez</button><div className={`sidebar-status ${status.kind}`}>{status.message}</div><div className="server-file-list"><div className="tree-root"><button className={`tree-item${!activeType ? ' active' : ''}`} onClick={() => selectType(null)}><span className="tree-icon">▾</span><span className="tree-name">masmarulez</span></button><div className="tree-children">{browseTypes.map((type) => <div key={type}><button className={`tree-item${activeType === type && !activeFolder ? ' active' : ''}`} onClick={() => selectType(type)} onContextMenu={(event) => menu(event, type)}><span className="tree-icon">{activeType === type ? '▾' : '▸'}</span><span className="tree-name">{type}</span></button>{activeType === type && <div className="tree-children">{folders(null).map(node)}</div>}</div>)}</div></div></div></aside>
}
