import type { ChatMessage, ChatRoom, InboxNotification } from './types'

function ago(minutes: number) {
  return new Date(Date.now() - minutes * 60_000).toISOString()
}

export const MOCK_NOTIFICATIONS: InboxNotification[] = [
  {
    id: 'n1',
    kind: 'barcode_request',
    title: '88코드 발급 요청',
    body: '김하늘 · M260931 블랙 M',
    href: '/barcodes',
    createdAt: ago(12),
    readAt: null,
  },
  {
    id: 'n2',
    kind: 'barcode_issued',
    title: '88코드 발급 완료',
    body: '8801234001284 · 봄 숄더백 블랙',
    href: '/barcodes',
    createdAt: ago(48),
    readAt: null,
  },
  {
    id: 'n3',
    kind: 'barcode_pending',
    title: 'M번호 미지정 바코드',
    body: '오늘 들어온 88코드 3건이 미지정입니다.',
    href: '/barcodes',
    createdAt: ago(90),
    readAt: null,
  },
  {
    id: 'n4',
    kind: 'outbound_changed',
    title: '바코드 출고 등록이 수정됨',
    body: '쿠팡 · 9/30 수량이 바뀌었습니다.',
    href: '/logistics/bulk-outbound',
    createdAt: ago(150),
    readAt: null,
  },
  {
    id: 'n5',
    kind: 'mention',
    title: '물류팀에서 언급',
    body: '이 바코드로 나간 건지 확인해 주세요.',
    href: '/barcodes',
    createdAt: ago(200),
    readAt: null,
  },
  {
    id: 'n6',
    kind: 'barcode_request',
    title: '88코드 발급 요청',
    body: '박서연 · M261002 아이보리 S',
    href: '/barcodes',
    createdAt: ago(260),
    readAt: null,
  },
  {
    id: 'n7',
    kind: 'outbound_changed',
    title: '바코드 출고 데이터입력',
    body: '스마트스토어 · 어제 등록이 추가됐습니다.',
    href: '/logistics/barcode-outbound-data-entry',
    createdAt: ago(60 * 26),
    readAt: ago(60 * 20),
  },
  {
    id: 'n8',
    kind: 'barcode_issued',
    title: '88코드 발급 완료',
    body: '8801234001215 · 미니 파우치 세트',
    href: '/barcodes',
    createdAt: ago(60 * 50),
    readAt: ago(60 * 48),
  },
]

export const MOCK_CHAT_ROOMS: ChatRoom[] = [
  {
    id: 'room-barcode',
    name: '88코드 발급',
    kind: 'group',
    lastMessage: 'M260931 블랙 M 하나 부탁해요.',
    lastAt: ago(8),
    unread: 2,
  },
  {
    id: 'room-logistics',
    name: '물류팀',
    kind: 'group',
    lastMessage: '쿠팡 9/30 수량은 반영했어요.',
    lastAt: ago(70),
    unread: 0,
  },
  {
    id: 'room-hana',
    name: '김하늘',
    kind: 'direct',
    lastMessage: '라벨은 발급되면 바로 뽑을게요.',
    lastAt: ago(18),
    unread: 1,
  },
  {
    id: 'room-md',
    name: 'MD',
    kind: 'group',
    lastMessage: '아이보리 S는 다음 주 입점이에요.',
    lastAt: ago(60 * 30),
    unread: 0,
  },
]

export const MOCK_CHAT_MESSAGES: ChatMessage[] = [
  {
    id: 'm1',
    roomId: 'room-barcode',
    authorName: '박서연',
    body: '오늘 요청 두 건 모아둘게요. 오후에 한 번에 발급해 주세요.',
    createdAt: ago(40),
    mine: false,
  },
  {
    id: 'm2',
    roomId: 'room-barcode',
    authorName: '나',
    body: '코리안넷에서 만들고 아틀리에에 올린 뒤 여기 남길게요.',
    createdAt: ago(28),
    mine: true,
  },
  {
    id: 'm3',
    roomId: 'room-barcode',
    authorName: '김하늘',
    body: 'M260931 블랙 M 하나 부탁해요.',
    createdAt: ago(8),
    mine: false,
  },
  {
    id: 'm4',
    roomId: 'room-logistics',
    authorName: '이준호',
    body: '쿠팡 9/30 출고 수량이 엑셀이랑 달라요.',
    createdAt: ago(180),
    mine: false,
  },
  {
    id: 'm5',
    roomId: 'room-logistics',
    authorName: '나',
    body: '등록 이력에서 방금 고쳤습니다.',
    createdAt: ago(90),
    mine: true,
  },
  {
    id: 'm6',
    roomId: 'room-logistics',
    authorName: '이준호',
    body: '쿠팡 9/30 수량은 반영했어요.',
    createdAt: ago(70),
    mine: false,
  },
  {
    id: 'm7',
    roomId: 'room-hana',
    authorName: '김하늘',
    body: '블랙 M 라벨은 몇 장 뽑으면 되나요?',
    createdAt: ago(50),
    mine: false,
  },
  {
    id: 'm8',
    roomId: 'room-hana',
    authorName: '나',
    body: '우선 20장만 뽑고, 번호는 발급된 뒤에 붙여요.',
    createdAt: ago(32),
    mine: true,
  },
  {
    id: 'm9',
    roomId: 'room-hana',
    authorName: '김하늘',
    body: '라벨은 발급되면 바로 뽑을게요.',
    createdAt: ago(18),
    mine: false,
  },
  {
    id: 'm10',
    roomId: 'room-md',
    authorName: '최민지',
    body: '아이보리 S는 다음 주 입점이에요. 코드 없으면 일정 밀려요.',
    createdAt: ago(60 * 32),
    mine: false,
  },
  {
    id: 'm11',
    roomId: 'room-md',
    authorName: '나',
    body: '발급 요청으로 올려 두었습니다.',
    createdAt: ago(60 * 30),
    mine: true,
  },
]
